# 模型相关配置
model:
  n_channels: 3 
  n_classes: 3 
  cutoff_ratio: 0.1  
  ch: 128
  out_ch: 3
  ch_mult: [1, 2, 2, 2]
  num_res_blocks: 2
  attn_resolutions: [16]
  dropout: 0.1
  in_channels: 3 
  pred_channels: 12
  other_channels_begin: 0
  resamp_with_conv: True
  patch_size: 15
  omega: 0.95
  top_k: 0.001
  radius: 20
  eps: 0.0001

# 优化器相关配置
optim:
  lr: 0.0004  # 学习率
  betas: [0.8, 0.999]  # Adam优化器的betas参数
  save_path: '/opt/data/private/diffuse model/wylmodel/train_result/best_dehazing_hunet.pth'  
  wavelet_params_path: '/opt/data/private/diffuse model/wylmodel/wavelet_weights_c2.pkl'  

# 训练相关配置
training:
  n_epochs: 100  
  epochs: 20  
  batch_size: 8  
  validation_freq: 5  
  use_mse: True 
  snapshot_freq: 10  
  use_gt_in_train: False  
  loss_type: 'MSELoss'

# 数据相关配置
data:
  data_dir: '/opt/data/private/diffuse model/data/RSHaze'  
  train_dir: '/opt/data/private/diffuse model/data/RSHaze'  
  val_dir: '/opt/data/private/diffuse model/data/RSHaze'  
  image_size: 256 
  num_workers: 4  
  conditional: True  
  use_window: False  
  window_size: 16  
  fourier_in_unet: True  
  global_attn: False  
  device: 'cuda'  
  begin_from_noise: True 
  val_ratio: 0.1

device: 'cuda'  

diffusion:
  schedule: 'linear'  
  linear_start: 0.0001  
  linear_end: 0.02  
  n_timesteps: 800  

